# NUMPY:
    
    It is an open-source Python library, designed by C programming language for:
    Numerical Computation
    Array Processing
    Mathematical Operations
    Linear Algebra
    Statistics
    Matrix Operation
    Random Number Generation
    Scientific Computing
    ML Operation

    Is is homogenous N-dimensional array.

    Provides:
    1. An array object of arbitrary homogenous items.
    2. Fast mathematical operations over arrays.
    3. Linear Algebra, Fourier Transformations, 

    It is called Numerical Python.

    Numpy ---->
        Pandas
        scikit-learn
        Tensorflow
        Pytorch
        scipy
        matplotlib
        seaborn

    If you understand Numpy, you will understand the above mentioned libraries too.

In [2]:
import numpy as np 

In [15]:
number = [10, 29, 20, 34, 32, 56, 54]

num_2 = []

for i in number:
    num_2.append(i * 2)
print(num_2)

[20, 58, 40, 68, 64, 112, 108]


In [19]:
number = [10, 29, 20, 34, 32, 56, 54]

a = np.array(number)
print(a*2)

# You don't need to use a for loop to multiply each element by 2.

[ 20  58  40  68  64 112 108]


# Diff:
    Features                |        List              |           Array
    Numerical Operation     |       Limited            |         Excellent
    Speed                   |        Slower            |          Faster
    Memory                  |         More             |           Less
    Vectorization           |          No              |           Yes
    Math Operation          |    Less Convenient       |     Very Convenient 
    Multi-dimensional Data  | Possible inconvenient    |         Excellent 
    ML/DS Use               |         Limited          |     Extremely Common

# Creating Numpy Array
    Numpy Array generally stores elements of the same data type.
    All elements in the array are same.

In [21]:
array = np.array([1, 2, 3, 4, 5, 12.34])
print(array)
type(array)

[ 1.    2.    3.    4.    5.   12.34]


numpy.ndarray

In [28]:
# 2D Array

list = [[1, 2, 3], [11, 22, 33]]

a = np.array(list)
a

array([[ 1,  2,  3],
       [11, 22, 33]])

In [29]:
a.ndim

2

# np.zeros()
    Initializing Matrix
    Neural Network Weights
    

In [35]:
# np.zeros(rows, columns) - Create an array of zeros

np.zeros((4, 2), dtype=str)

array([['', ''],
       ['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [36]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.full((2, 2), 8)

array([[8, 8],
       [8, 8]])

In [49]:
np.empty((2, 2), dtype=int)

array([[            0, 2246421119040],
       [2246421118880, 2246421119600]])

In [50]:
np.linspace(start=1, stop=2, retstep=True)

(array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
        1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
        1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
        1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
        1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
        1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
        1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
        1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
        1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
        1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ]),
 np.float64(0.02040816326530612))

# shape:
    Return the dimension vectors.

# 

In [53]:
ar = [[1, 2, 3, 4],
      [11, 22, 33, 44]]

ar = np.array(ar, dtype="int16")
print(f"Dimension of Array = {ar.ndim}")

print(f"Shape of Array is = {ar.shape}")

Dimension of Array = 2
Shape of Array is = (2, 4)


In [54]:
ar.dtype

dtype('int16')