# NumPy
    NumPy stands for Numerical Python.
    It is a Python libraby used for numerical computing.
    It is widely used in:
        -> Data Science
        -> Engineering
        -> AI & Machine Learning
    It is written in C, which is comparatively faster than Python.
    It is used to handle large scale numerical operations efficiently. 
    pip install numpy ----> Used to download NumPy

In [1]:
import numpy as np

print(np.__version__)

2.5.2


In [5]:
my_list = [1, 2, 3, 4]
print(my_list * 2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
array = np.array([1, 2, 3, 4])
print(array)
print(type(array))
print(array * 2)

[1 2 3 4]
<class 'numpy.ndarray'>


array([2, 4, 6, 8])

In [9]:
array = np.array([1, 2, 3, 4])
print(array * 3)

[ 3  6  9 12]
